apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-k8s-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-k8s-demo
  template:
    metadata:
      labels:
        app: tomcat-k8s-demo
    spec:
      containers:
        - name: tomcat
          image: tomcat-k8s-demo:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080